version: '3.8'

services:
  frontend:  # Renamed from 'app' to 'frontend' to be more explicit
    image: bitbots_frontend:${VERSION:-latest}
    build:
      context: https://github.com/Musicdude45678/BitBots.git#main
      dockerfile: Dockerfile
      args:
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
        - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
        - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
        - VITE_APP_ENV=${VITE_APP_ENV:-production}
      no_cache: true
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
